welkomstTekst: > 
  Welkom!

  Ik ben de FlynnBot!

  Wat leuk dat jij in de afwezigheid van Robin met mij het avontuur aan wilt gaan.
  
keuzeTekst: >
  Wat zullen we gaan doen?

  Combat of RP?

stilteTekst: >
  Dit vindt Flynn niet fijn.

  Zet die persoon op zijn plek!

andersTekst: >
  Levert de deal me 1 van de volgende zaken op?
    - Geld
    - Vrienden
    - Memes
    - Kan ik mijn skills laten zien?

sheev: >
  """
                      ..,,.   ........,,,*/ ......,      .  ..                    
          ..,,.   .........,,*( ,.......     .   . ..  .              
      ....,,**/((,.........,,** .* .... /@@@@@@@@@% , %@@@@@@@@    .  
  .......,,,,*/////(%,,....,,*. .,* ... /@@@@ .@@@@ .(@@@@ *@@@@      
  ...........,,,***/(#(%#,,,,,**  ..,* .. /@@@@ .@@@@. #@@@@ *@@@@ .....
  ............,,,**//(#%%%/,,,,*,  ..,,* . /@@@@ .@@@@. %@@@@ *@@@@  ....
  ............,,,***/((((%&*,,,*,   ..,,*/  /@@@@ .@@@@. #@@@@ *@@@@ ,...,
  ......   ...**/**(///##%,,,*,.  ....,,/* /@@@@ ,@@@@ .(@@@@ (@@@@ *****
  ........,,, ,...,/*/(#(#*,**,  ......,,/ /@@@@@@@@@@ * *@@@@@@@@  ***,,
  .. .......,.....,(/(###***,   ......,,*(......, #@@@@* @@@@@@@@@@@ ...
  . .......*,,.,*((#/##*..    .......,,*/ ......#@@@@* @@@@@@@@@@@    
  ... .....*,.,**(.*/(#..        .....,,(*..... #@@@@*    @@@@&       
    ., .....,,.,,*//(((,             ...,*/ .... #@@@@*    @@@@&       
        ....,,,,,**/(#(.                .,** ... #@@@@*    @@@@&       
        ....,,,**/(((..                    .  . #@@@@*    @@@@&       
          ..,,,,*///,.                        .. #@@@@*    @@@@&       
            .,**,  .                             #@@@@*    @@@@&       
                                                      . ...  ...      
                                                          .............

  """