Flynn:
  characterClass: Rogue
  level: 7
  hitpoints: 40
  race: human
  ac: 14
  weapons:
    1: Eduard Triponkie
    2: Dagger

Brando:
  characterClass: Fighter
  subClass: Battlemaster
  level: 7
  hitpoints: 63
  race: human
  ac: 16
  weapons:
    1: Glaive +1
  attributes:
    strength: 20
    dexterity: 12
    constitution: 16
    intelligince: 8
    wisdom: 12
    charisma: 8
  attackAttribute: strength
